#Сервис для баллансировки между подами приложения по портам
apiVersion: v1
kind: Service
metadata:
  #Имя сервиса
  name: nginx-test-service
spec:
  #Тип сервиса 
  type: ClusterIP
  selector:
    #Селектор по которому сервис будет искать приложение, к которому оно принадлежит
    app: nginx-test
  ports:
  - name: nginx-test-service-port
    protocol: TCP
    #Порт котору слушает сервис
    port: 80
    #Порт прилложения, в которое будет перенаправлять порт 
    #Можно указать имя порта. Тогда номер не важен, сервис будет целиться в любой порт приложения с нужным именем.
    targetPort: 80